### PR TITLE
Allow for custom Authorization header

### PR DESCRIPTION
**Pull request by zlorb**
Different systems require different authorization header, such as 'Bearer' header.

### CODE REVIEW

**Comment by tgs** [comment]
I guess you've tested this in your system?  This will still put everything under the "Authorization" HTTP header, although with a customizable text.

**Comment by zlorb** [comment]
Yes, I tested this on my system. 

Thanks in advance,
Zohar

**Comment by tgs** [comment]
I'm going to change the name of the method, actually, so that it's clear that it's changing the contents of the header but not the HTTP header itself.  I'm sorry for breaking your existing code, but it should just be a find-and-replace for you.

**Comment by tgs** [comment]
I've changed it to .set_header_format(new_format), and the constructor kwarg is now header_format.

I'll release version 0.4 with these changes soon, probably tonight or tomorrow.

**Comment by zlorb** [comment]
Great, thanks.

**Comment by tgs** [comment]
OK, it's released :)

**Comment by zlorb** [comment]
Thanks for the quick turn-around.

**Comment by tgs** [comment]
No problem :)

**Pull request merged**
